name: Release

on:
  push:
    branches:
      - main

permissions: {}
jobs:
  release:
    permissions:
      contents: write # to create release (changesets/action)
      pull-requests: write # to create pull request (changesets/action)

    name: ${{ matrix.channel }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        channel:
          - latest
          - dev

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: yarn
          registry-url: https://registry.npmjs.org
          key: node18

      - name: Install dependencies
        run: yarn

      - name: Prepare release
        run: yarn prerelease
